config/routes.rb
Rails.application.routes.draw do

  resources :cars

  get '/usados', to: 'cars#usados'
  get '/novos', to: 'cars#news'
  get '/luxo', to: 'cars#luxo'

  

  
  root 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
	scope :usados,    -> { where ("km > 0") }
	scope :novos,     -> { where ("km = 0 and value < 100000") }
	scope :luxos,     -> { where ("km = 0 and value >= 100000") }
	scope :destaques, -> { where ({featured: true}) }	
	
	validates_presence_of :brand, :model, :year, :km, :value, :fuel
  validates_numericality_of :year, :km, only_integer: true
  validates_numericality_of :km, greater_than_or_equal_to: 0
  validates_length_of :year, is: 4

	def second_hand?
		km > 0
	end

  def new_one?
    km == 0 && value < 100000
  end

  def luxury?
    km == 0 && value >= 100000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def show
    @car = Car.find_by_id(params[:id])
    redirect_to root_path unless @car
  end

  def new
    @car = Car.new
  end


  def create
    @car = Car.new(car_params)
    if @car.save 
      redirect_to @car
    else 
      render "new"
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def luxo
    @cars = Car.luxos
  end

  def index
    @cars = Car.all
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path 
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to @car 
  end

  def car_params
    params.require(:car).permit(:model, :year, :brand, :km, :value, :motor, :technical_details, :featured, :fuel)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@cars = Car.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_car.html.erb
 <div class="row">
	    <div class="col-md-4 col-sm-10">
	        <%= link_to image_tag("carro01.jpg", class: "img-responsive img-rounded"), car %>
	    </div>
	    <div class="col-md-7 col-sm-10">
	      <div class="row">
	        <ul class="well">
	        	<li class=	"list-group-item"><%= link_to "#{car.model} - #{car.brand}", car %></li>
	        	<li class="list-group-item">Preço: <%= number_to_currency(car.value, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %></li>
	        	<li class="list-group-item">Ano: <%= car.year %></li>
	        	<li class="list-group-item">KM: <%= number_with_delimiter(car.km, delimiter: ".", separator: "") %></li>
	        	<li class="list-group-item">Motor: <%= car.motor %></li>
	        	<li class="list-group-item">Combustível: <%= car.fuel %></li>
	        </ul>
	      </div>	        
	   	</div>
 	</div>
 	<hr>
	   		

app/views/cars/_form.html.erb
<%= form_for @car do |c| %>

  <% if @car.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@car.errors.count, "error") %> *Os campos são obrigatórios!
        </h2>
        <ul>
          <% @car.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

	<div class="form-group">
    <label >Marca*</label>
    <%= c.text_field :brand, class:"form-control"%>
   </div>

   <div class="form-group">
    <label >Modelo*</label>
    <%= c.text_field :model, class:"form-control"%>
  </div>

  <div class="form-group">
    <label >Ano*</label>
    <%= c.number_field :year, class:"form-control"%>
  </div>

  <div class="form-group">
    <label >Km*</label>
    <%= c.number_field :km, class:"form-control"%>
  </div>

  <div class="form-group">
    <label >Motor</label>
    <%= c.text_field :motor, class:"form-control"%>
  </div>
  
  <div class="form-group">
    <label >Combustível</label>
    <%= c.select :fuel, ["Gasolina", "Alcool", "Diesel", "Flex"], class:"form-control"%>
  </div>

  <div class="form-group">
    <label >Valor R$*</label>
    <%= c.text_field :value, class:"form-control"%>
  </div>
  <div class="form-group">
    <label >Detalhes Técnicos</label>
    <%= c.text_area :technical_details, class:"form-control", rows: 3%>
  </div>
  <div class="form-group">
    <label >Destaque</label>
    <%= c.check_box :featured%>
  </div>
  <button type="submit" class="btn btn-primary">Salvar</button>
<% end %>

app/views/cars/edit.html.erb
<h1>Edição do carro</h1>

<%= render 'form'%>

app/views/cars/index.html.erb
<h1>Lista de todos os carros</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Marca</th>
      <th>Ano</th>
      <th>Km</th>
      <th>Motor</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.brand %></td>
        <td><%= car.year %></td>
        <td><%= car.km %></td>
        <td><%= car.motor %></td>
        <td><%= car.value %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/luxo.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></option>
  <li>Carros de Luxo</option>
  <li class="active"></option>
</ol>
<section>
    <%= render partial: "car", collection: @cars %>
</section>

app/views/cars/new.html.erb
<h1>Cadastrar Carro</h1>

<%= render 'form'%>

app/views/cars/news.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></option>
  <li>Carros novos</option>
  <li class="active"></option>
</ol>
<section>
  <% Car.novos.each do |car| %>
    <%= render partial: "car", locals: { car: car } %>
  <%end%>
</section>

app/views/cars/show.html.erb
<h1><%= "Detalhes de #{@car.model} #{@car.brand}"%></h1>
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></option>
  <li>Detalhes</option>
  <li class="active"><%= "#{@car.model} - #{@car.brand}" %></option>
</ol>
<section>
  <div class="row">
    <div class="col-md-6 col-sm-12">
        <%= image_tag "carro01.jpg", class: "img-responsive" %>
    </div>
    <div class="col-md-6 col-sm-12">
      <div class="row">
        <h1><%= @car.model + " - " + @car.brand %>  </h1>
        <h2>Preço: <span id="preco_carro"><%= number_to_currency(@car.value, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %></span> <small>(com financiamento)</small></h2>            
        <ul class="list-unstyled">
          <li>Ano: <%= @car.year %></option> 
          <li>KM: <%= number_with_delimiter(@car.km, delimiter: ".", separator: "") %></option> 
          <li>Motor: <%= @car.motor %></option>
          <li>Motor: <%= @car.fuel %></option> 
        </ul>
        <button class="btn btn-danger hidden-print">Comprar</button>
        <button class="btn btn-success hidden-print" onclick="financiamento()">Detalhes Financiamento</button>
             
      <div class="row">
        <div class="col-md-12 invisible" id="financiamento">
          <h3>Detalhes do Financiamento</h3>
          <div class="container-fluid" id="detalhes_do_financiamento"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12" id="entrada">
        	<form class="form-inline" onsubmit="return false;">
        	<input type="text" id="valor_entrada" class="form-control"></input>
				<select id="quantidade_parcelas" class="form-control">
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">Número de parcelas</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">01</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">02</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">03</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">04</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">05</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">06</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">07</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">08</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">09</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">10</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">11</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">12</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">13</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">14</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">15</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">16</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">17</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">18</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">19</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">20</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">21</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">22</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">23</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">24</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">25</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">26</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">27</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">28</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">29</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">30</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">31</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">32</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">33</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">34</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">35</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">36</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">37</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">38</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">39</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">40</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">41</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">42</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">43</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">44</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">45</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">46</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">47</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">48</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">49</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">50</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">51</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">52</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">53</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">54</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">55</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">56</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">57</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">58</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">59</a></option>
				<option role="presentation"><a role="menuitem" tabindex="-1" href="#">60</a></option>

		   </select>
      <button class="btn  btn-default" onclick="financiamento(12)">Calcular com entrada</button>
     </form>
      </div>
      </div>

    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <ul class="nav nav-tabs" id="tabs_kars">
        <li class="active"><a href="#dados_anunciante">Dados Anuncianente</a></option>
        <li><a href="#detalhes_tecnicos">Detalhes Tecnicos</a></option>
        <li><a href="#detalhes_financiamento">Detalhes Financiamento</a></option>
      </ul>
      <div class="tab-content">
        <div  id="dados_anunciante" class="tab-pane fade in active">
          <h3>Dados do Anunciante</h3>
          <p>dafd fadsf dfafd fadfd afafd adsf dfa dfa fdsf adf adf adf dsafd fasdf asdf dsaf dsfad daf ds</p>
        </div> 
        <div id="detalhes_tecnicos" class="tab-pane fade">
          <h3>Detalhes Tecnicos</h3>
          <p><%= @car.technical_details%></p>
        </div>
        <div id="detalhes_financiamento" class="tab-pane fade">
          <h3>Detalhes do Financiamento</h3>
          <p>dafd fadsf dfafd fadfd afafd adsf dfa dfa fdsf adf adf adf dsafd fasdf asdf dsaf dsfad daf ds</p>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
  $('#tabs_kars a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/cars/usados.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></option>
  <li>Carros Usados</option>
  <li class="active"></option>
</ol>
<section>
  <% Car.usados.each do |car| %>
    <%= render partial: "car", locals: { car: car } %>
  <%end%>
</section>

app/views/home/index.html.erb
    <section id="destaques" class="row">
      <div class="col-md-12">
        <div id="carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @cars.destaques.each_index do |index|%>
              <li data-target="#carousel" data-slide-to="<%= index %>" class="<%="active" if index == 0 %>"></li>
            <%end%>
          </ol>
          <div class="carousel-inner" role="listbox">
            <% @cars.destaques.each_index do |index|%>
              <%if index == 0%>
                <div class="item active">
              <% else %>
                <div class="item">
              <% end %>
              	<%= image_tag "carro01.jpg"%>
                <div class= "carousel-caption">
                  <%= @cars.destaques[index].model%>
                  <%= @cars.destaques[index].brand%>
                  <%= "#{@cars.destaques[index].km} Km"%>
                  <%= "R$: #{@cars.destaques[index].value}"%>
                </div>
              </div>
            <% end %>
          </div>
          <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
          </a>
          <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Próximo</span>
          </a>
        </div>
      </div>
    </section>
    <br>
    <section id="anuncios" >
    <% @cars.limit(6).each_index do |index|%>
      <% if index == 0 || (index % 3) == 0 %>
        <div class="row">
      <% end %>
         <div class="col-md-4">
            <div class="thumbnail">
              <%= image_tag "carro03.jpg"%>
              <div class="caption">
                <h3><%= @cars[index].model %></h3>
                <p><%= @cars[index].value %></p>
                <p>
                  Marca: <%=@cars[index].brand%><br>
                  Ano:<%=@cars[index].year%><br>
                  Km Rodados: <%=@cars[index].km%><br>
                  Motor: <%=@cars[index].motor%><br>
                  Combustível: <%=@cars[index].fuel%>
                </p>
                <%= link_to "Comprar", @cars[index] , class: "btn btn-primary"%>
              </div>
            </div>
          </div>
      <% if (index%3) == 2 || index == @cars.length - 1 %>
        </div>
      <% end %>
    <% end %>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KarsRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
	  <nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
			  <div class="navbar-header">
	    		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	          <span class="sr-only">Toggle navigation</span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
          <%= link_to "Kars", root_path, class: "navbar-brand" %>
	      </div>
	      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	        <ul class="nav navbar-nav">
	      	  <li><%= link_to "Novos", novos_path %></li>
	          <li><%= link_to "Usados", usados_path %></li>
	          <li><%= link_to "Luxo", luxo_path %></li>
	          <li><a href="#">Contato</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <%= yield %>
	</div>
</body>
</html>